version: "2.4"
services:
  client:
    image: node:16.15-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - "${PWD:-./}:/app"
    ports:
      - "3000:3000"
